apiVersion: v1
kind: Service
metadata:
  name: nucoin-backend-auth-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: nucoin-backend-auth-service
  ports:
    - port: 3002
      targetPort: 3002